# Основные настройки (необходимо заполнить)
api:
  # Ключ API OpenAI
  openai_api_key: "ваш_api_ключ"

# Настройки работы бота (опционально, можно изменить для персонализации)
settings:
  prompt_tone: "дружелюбный"  # Тон сообщения (должен быть в кавычках)
  join_chat_delay: 10-30      # Задержка перед вступлением в чат (в секундах)
  send_message_delay: 15-30   # Диапазон задержки перед отправкой сообщения
  message_limit: 2            # Кол-во сообщений перед сменой аккаунта
  reaction_mode: "keywords"   # Режим реакции: "keywords" или "interval"
  reaction_interval: 10       # Интервал сообщений для реакции (если режим "interval")
  keywords_file: "key.txt"    # Файл с ключевыми словами (если режим "keywords")