name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Create config and data files
        run: |
          mkdir -p config data
          # Создаем config/config.yaml
          cat <<EOF > config/config.yaml
          api:
            openai_api_key: "${{ secrets.OPENAI_API_KEY }}"
            chat_gpt_model: "gpt-3.5-turbo"
          settings:
            prompt_tone: "дружелюбный"
            join_delay: "10-30"
            send_message_delay: "15-30"
            message_limit: 2
            reaction_mode: "keywords"
            reaction_interval: 10
            keywords_file: "data/key.txt"
          EOF

          # Создаем data/prompts.txt
          echo "Write a {prompt_tone} response to: {message_text}" > data/prompts.txt

          # Создаем data/key.txt
          echo "keyword1\nkeyword2" > data/key.txt

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install

      - name: Run tests
        run: |
          poetry run pytest tests/