name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Установка Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Create config and data files
        run: |
          mkdir -p config data
          echo "openai_api_key: ${{ secrets.OPENAI_API_KEY }}" > config/config.yaml
          echo "Write a {prompt_tone} response to: {message_text}" > data/prompts.txt
          echo "keyword1\nkeyword2" > data/key.txt

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install

      - name: Run tests
        run: |
          poetry run pytest tests/